---
- name: ancinga
  vars:
     port_contents: "{{ lookup('file', 'port') }}"
     NAME_contents: "{{ lookup('file', 'NAME') }}"
  hosts: "{{ NAME_contents }}"
  sudo: True
  tasks:
  - name: Icinga2
    docker:
      name: "{{ NAME_contents }}"
      image: icinga/icinga2
      state: reloaded
      restart_policy: always
      ports:
      - "{{ port_contents }}"
      volumes:
      - '/tmp:/tmp'
